### ISSUE TITLE
journal-mailer hangs when sendmail doesn't terminate

### ISSUE THREAD

**Issue by soenkehahn** [zalora/journal-mailer#17]
There was an instance where `journal-mailer` stopped working, because it invoked `sendmail` and that didn't terminate. `journal-mailer` became unresponsive due to that. We should figure out, why this happened.

Maybe we should have a timeout on `sendmail` invocations in any case?

**Comment by fmap** [comment]
Why not just fork the process?

**Comment by soenkehahn** [comment]
Then we would have a dangling `sendmail` process. While this would keep `journal-mailer` in a responsive state, I don't think it's better. Why would you prefer that?
